<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_new</name>
   <tag></tag>
   <elementGuidId>072bc5e4-a338-4e14-99ed-951b5a77ce29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;example_wrapper&quot;]/div[1]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;example_wrapper&quot;]/div[1]/button[1]</value>
   </webElementProperties>
</WebElementEntity>
