<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_enviar</name>
   <tag></tag>
   <elementGuidId>4fa5936e-7596-4d58-a778-e2a6d9d36994</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mG61Hd&quot;]/div/div[2]/div[3]/div[1]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mG61Hd&quot;]/div/div[2]/div[3]/div[1]/div/div</value>
   </webElementProperties>
</WebElementEntity>
