<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radioBtnTipo</name>
   <tag></tag>
   <elementGuidId>ae57a53a-3cc1-41e1-ab39-92c60b3f8c3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>${xpath}</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>${xpath}</value>
   </webElementProperties>
</WebElementEntity>
