<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_donde</name>
   <tag></tag>
   <elementGuidId>1212fee1-b0c6-4321-8edc-28e0456bdf1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mG61Hd&quot;]/div/div[2]/div[2]/div[6]/div/div[2]/div/div[1]/div/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mG61Hd&quot;]/div/div[2]/div[2]/div[6]/div/div[2]/div/div[1]/div/div[1]/input</value>
   </webElementProperties>
</WebElementEntity>
